### ISSUE TITLE
Cannot use `import` statements

### ISSUE THREAD

**Issue by willin** [casual-simulation/node-deno-vm#20]
```
[deno] Download https://deno.land/std/encoding/base64.ts

[deno] Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/base64.ts

[deno] Download https://deno.land/std@0.170.0/encoding/base64.ts

[deno] error: Uncaught SyntaxError: Cannot use import statement outside a module
            Function(script)();
            ^
    at Function (<anonymous>)
    at WebSocket.socket.onopen (file:///Users/v0/Desktop/demo/node_modules/deno-vm/deno/index.ts:44:13)
    at WebSocket.wrappedHandler (deno:ext/web/02_event.js:1383:14)
    at innerInvokeEventListeners (deno:ext/web/02_event.js:775:9)
    at invokeEventListeners (deno:ext/web/02_event.js:815:7)
    at dispatch (deno:ext/web/02_event.js:684:11)
    at WebSocket.dispatchEvent (deno:ext/web/02_event.js:1063:14)
    at WebSocket.PromisePrototypeThen.<computed> (deno:ext/websocket/01_websocket.js:265:18)
```

Demo codes:

```ts
import { DenoWorker } from 'deno-vm';

const script = `
    import axiod from 'https://deno.land/x/axiod/mod.ts';
    
    axiod.get("https://www.baidu.com").then((response) => {
        self.postMessage(response);
    });
    self.onmessage = (e) => {
        self.postMessage(e.data * 2);
    };
`;

const worker = new DenoWorker(script, {
  permissions: {
    allowNet: ['baidu.com', '127.0.0.1']
  }
});

worker.onmessage = (e) => {
  console.log('Number: ' + e.data);
};

worker.postMessage(2);
// Number: 4
```

**Comment by KallynGowdy** [comment]
So, currently import statements are only supported if a URL object is passed to `DenoWorker`. It may be possible to modify `DenoWorker` to support string scripts that have import statements, but for now it is not possible.

**Comment by willin** [comment]
> So, currently import statements are only supported if a URL object is passed to `DenoWorker`. It may be possible to modify `DenoWorker` to support string scripts that have import statements, but for now it is not possible.


```ts
const worker = new DenoWorker('https://mydomain.com/script.ts', {
  permissions: {
    allowNet: true
  }
});
```

like this?

**Comment by KallynGowdy** [comment]
Yes, just like that

**Comment by KallynGowdy** [comment]
No, like this: 
```typescript
const worker = new DenoWorker(new URL('https://mydomain.com/script.ts'), {
  permissions: {
    allowNet: true
  }
});
```

**Comment by patrickjm** [comment]
Been able to get around this using file urls

```ts
new DenoWorker(new URL("file://" + scriptPath), { // <--- path must be prefixed with file://
    permissions: {
        allowRead: [scriptPath] // <----- path must *not* be prefixed with file://
    }
})
```

Not sure exactly how this would fare on Windows or in a path containing spaces, though
